from django.db import models

class StudentPerformance(models.Model):
    gender = models.CharField(max_length=32)
    race_ethnicity = models.CharField(max_length=50)
    parental_level_of_education =  models.CharField(max_length=50)
    lunch = models.CharField(max_length=32)
    test_preparation_course = models.CharField(max_length=50)
    reading_score = models.IntegerField()
    math_score = models.IntegerField()

class Titanic(models.Model):
    Pclass = models.IntegerField()
    Sex = models.CharField(max_length=77)
    Age = models.IntegerField()
    SibSp = models.IntegerField()
    Parch = models.IntegerField()
    Fare = models.FloatField()
    SibParch = models.IntegerField()
    Embarked = models.CharField(max_length=77)

class House(models.Model):
    GrLivArea = models.IntegerField()
    YearBuilt = models.IntegerField()
    GarageCars = models.IntegerField()
    TotalBsmtSF = models.IntegerField()
    FullBath = models.IntegerField()
    OverallQual = models.IntegerField()
    Neighborhood = models.CharField(max_length=77)

class Bank(models.Model):
    person_age = models.IntegerField()
    person_gender = models.CharField(max_length=77)
    person_education = models.CharField(max_length=77)
    person_income = models.IntegerField()
    person_emp_exp = models.IntegerField()
    person_home_ownership = models.CharField(max_length=77)
    loan_amnt = models.IntegerField()
    loan_intent = models.CharField(max_length=77)
    loan_int_rate = models.FloatField()
    loan_percent_income = models.FloatField()
    cb_person_cred_hist_length = models.IntegerField()
    credit_score = models.IntegerField()
    previous_loan_defaults_on_file = models.CharField(max_length=77)

class Diabetes(models.Model):
    Pregnancies = models.IntegerField()
    Glucose = models.IntegerField()
    BloodPressure = models.IntegerField()
    SkinThickness = models.IntegerField()
    Insulin = models.IntegerField()
    BMI = models.FloatField()
    DiabetesPedigreeFunction = models.FloatField()
    Age = models.IntegerField()

class Avocado(models.Model):
    firmness = models.FloatField()
    hue = models.IntegerField()
    saturation = models.IntegerField()
    brightness = models.IntegerField()
    sound_db = models.IntegerField()
    weight_g = models.IntegerField()
    size_cm3 = models.IntegerField()
    color_category = models.CharField(max_length=32)

class Mushroom(models.Model):
    cap_shape = models.CharField(max_length=77)
    cap_surface = models.CharField(max_length=77)
    cap_color = models.CharField(max_length=77)
    bruises = models.CharField(max_length=77)
    odor = models.CharField(max_length=77)
    gill_attachment = models.CharField(max_length=77)
    gill_spacing = models.CharField(max_length=77)
    gill_size = models.CharField(max_length=77)
    gill_color = models.CharField(max_length=77)
    stalk_shape = models.CharField(max_length=77)
    stalk_root = models.CharField(max_length=77)
    stalk_surface_above_ring = models.CharField(max_length=77)
    stalk_surface_below_ring = models.CharField(max_length=77)
    stalk_color_above_ring = models.CharField(max_length=77)
    stalk_color_below_ring = models.CharField(max_length=77)
    veil_color = models.CharField(max_length=77)
    veil_type = models.CharField(max_length=77)
    ring_number = models.CharField(max_length=77)
    ring_type = models.CharField(max_length=77)
    spore_print_color = models.CharField(max_length=77)
    population = models.CharField(max_length=77)
    habitat = models.CharField(max_length=77)


class Telecom(models.Model):
    gender = models.CharField(max_length=77)
    SeniorCitizen = models.IntegerField()
    Partner = models.CharField(max_length=77)
    Dependents = models.CharField(max_length=77)
    tenure = models.IntegerField()
    PhoneService = models.CharField(max_length=77)
    MultipleLines = models.CharField(max_length=77)
    InternetService = models.CharField(max_length=77)
    OnlineSecurity = models.CharField(max_length=77)
    OnlineBackup = models.CharField(max_length=77)
    DeviceProtection = models.CharField(max_length=77)
    TechSupport = models.CharField(max_length=77)
    StreamingTV = models.CharField(max_length=77)
    StreamingMovies = models.CharField(max_length=77)
    Contract = models.CharField(max_length=77)
    PaperlessBilling = models.CharField(max_length=77)
    PaymentMethod = models.CharField(max_length=77)
    MonthlyCharges = models.FloatField()
    TotalCharges = models.FloatField()

class HREmployee(models.Model):
    Age = models.IntegerField()
    DailyRate = models.IntegerField()
    DistanceFromHome = models.IntegerField()
    Education = models.IntegerField()
    EnvironmentSatisfaction = models.IntegerField()
    HourlyRate = models.IntegerField()
    JobInvolvement = models.IntegerField()
    JobLevel = models.IntegerField()
    JobSatisfaction = models.IntegerField()
    MonthlyIncome = models.IntegerField()
    MonthlyRate = models.IntegerField()
    NumCompaniesWorked = models.IntegerField()
    PercentSalaryHike = models.IntegerField()
    PerformanceRating = models.IntegerField()
    RelationshipSatisfaction = models.IntegerField()
    StockOptionLevel = models.IntegerField()
    TotalWorkingYears = models.IntegerField()
    TrainingTimesLastYear = models.IntegerField()
    WorkLifeBalance = models.IntegerField()
    YearsAtCompany = models.IntegerField()
    YearsInCurrentRole = models.IntegerField()
    YearsSinceLastPromotion = models.IntegerField()
    YearsWithCurrManager = models.IntegerField()
    BusinessTravel = models.CharField(max_length=77)
    Department = models.CharField(max_length=77)
    EducationField = models.CharField(max_length=77)
    Gender = models.CharField(max_length=77)
    JobRole = models.CharField(max_length=77)
    MaritalStatus = models.CharField(max_length=77)
    OverTime = models.CharField(max_length=77)