from rest_framework import serializers

class StudentPerformanceSerializers(serializers.Serializer):
    gender = serializers.CharField(max_length=77)
    race_ethnicity = serializers.CharField(max_length=77)
    parental_level_of_education =  serializers.CharField(max_length=77)
    lunch = serializers.CharField(max_length=77)
    test_preparation_course = serializers.CharField(max_length=77)
    reading_score = serializers.IntegerField()
    math_score = serializers.IntegerField()

class TitanicSerializers(serializers.Serializer):
    Pclass = serializers.IntegerField()
    Sex = serializers.CharField(max_length=77)
    Age = serializers.IntegerField()
    SibSp = serializers.IntegerField()
    Parch = serializers.IntegerField()
    Fare = serializers.FloatField()
    SibParch = serializers.IntegerField()
    Embarked = serializers.CharField(max_length=77)

class HouseSerializers(serializers.Serializer):
    GrLivArea = serializers.IntegerField()
    YearBuilt = serializers.IntegerField()
    GarageCars = serializers.IntegerField()
    TotalBsmtSF = serializers.IntegerField()
    FullBath = serializers.IntegerField()
    OverallQual = serializers.IntegerField()
    Neighborhood = serializers.CharField(max_length=77)

class BankSerializers(serializers.Serializer):
    person_age = serializers.IntegerField()
    person_gender = serializers.CharField(max_length=77)
    person_education = serializers.CharField(max_length=77)
    person_income = serializers.IntegerField()
    person_emp_exp = serializers.IntegerField()
    person_home_ownership = serializers.CharField(max_length=77)
    loan_amnt = serializers.IntegerField()
    loan_intent = serializers.CharField(max_length=77)
    loan_int_rate = serializers.FloatField()
    loan_percent_income = serializers.FloatField()
    cb_person_cred_hist_length = serializers.IntegerField()
    credit_score = serializers.IntegerField()
    previous_loan_defaults_on_file = serializers.CharField(max_length=77)

class DiabetesSerializers(serializers.Serializer):
    Pregnancies = serializers.IntegerField()
    Glucose = serializers.IntegerField()
    BloodPressure = serializers.IntegerField()
    SkinThickness = serializers.IntegerField()
    Insulin = serializers.IntegerField()
    BMI = serializers.FloatField()
    DiabetesPedigreeFunction = serializers.FloatField()
    Age = serializers.IntegerField()

class AvocadoSerializers(serializers.Serializer):
    firmness = serializers.FloatField()
    hue = serializers.IntegerField()
    saturation = serializers.IntegerField()
    brightness = serializers.IntegerField()
    sound_db = serializers.IntegerField()
    weight_g = serializers.IntegerField()
    size_cm3 = serializers.IntegerField()
    color_category = serializers.CharField(max_length=77)

class MushroomSerializers(serializers.Serializer):
    cap_shape = serializers.CharField(max_length=77)
    cap_surface = serializers.CharField(max_length=77)
    cap_color = serializers.CharField(max_length=77)
    bruises = serializers.CharField(max_length=77)
    odor = serializers.CharField(max_length=77)
    gill_attachment = serializers.CharField(max_length=77)
    gill_spacing = serializers.CharField(max_length=77)
    gill_size = serializers.CharField(max_length=77)
    gill_color = serializers.CharField(max_length=77)
    stalk_shape = serializers.CharField(max_length=77)
    stalk_root = serializers.CharField(max_length=77)
    stalk_surface_above_ring = serializers.CharField(max_length=77)
    stalk_surface_below_ring = serializers.CharField(max_length=77)
    stalk_color_above_ring = serializers.CharField(max_length=77)
    stalk_color_below_ring = serializers.CharField(max_length=77)
    veil_color = serializers.CharField(max_length=77)
    veil_type = serializers.CharField(max_length=77)
    ring_number = serializers.CharField(max_length=77)
    ring_type = serializers.CharField(max_length=77)
    spore_print_color = serializers.CharField(max_length=77)
    population = serializers.CharField(max_length=77)
    habitat = serializers.CharField(max_length=77)

class TelecomSerializers(serializers.Serializer):
    gender = serializers.CharField(max_length=77)
    SeniorCitizen = serializers.IntegerField()
    Partner = serializers.CharField(max_length=77)
    Dependents = serializers.CharField(max_length=77)
    tenure = serializers.IntegerField()
    PhoneService = serializers.CharField(max_length=77)
    MultipleLines = serializers.CharField(max_length=77)
    InternetService = serializers.CharField(max_length=77)
    OnlineSecurity = serializers.CharField(max_length=77)
    OnlineBackup = serializers.CharField(max_length=77)
    DeviceProtection = serializers.CharField(max_length=77)
    TechSupport = serializers.CharField(max_length=77)
    StreamingTV = serializers.CharField(max_length=77)
    StreamingMovies = serializers.CharField(max_length=77)
    Contract = serializers.CharField(max_length=77)
    PaperlessBilling = serializers.CharField(max_length=77)
    PaymentMethod = serializers.CharField(max_length=77)
    MonthlyCharges = serializers.FloatField()
    TotalCharges = serializers.FloatField()


class HREmployeeSerializers(serializers.Serializer):
    Age = serializers.IntegerField()
    DailyRate = serializers.IntegerField()
    DistanceFromHome = serializers.IntegerField()
    Education = serializers.IntegerField()
    EnvironmentSatisfaction = serializers.IntegerField()
    HourlyRate = serializers.IntegerField()
    JobInvolvement = serializers.IntegerField()
    JobLevel = serializers.IntegerField()
    JobSatisfaction = serializers.IntegerField()
    MonthlyIncome = serializers.IntegerField()
    MonthlyRate = serializers.IntegerField()
    NumCompaniesWorked = serializers.IntegerField()
    PercentSalaryHike = serializers.IntegerField()
    PerformanceRating = serializers.IntegerField()
    RelationshipSatisfaction = serializers.IntegerField()
    StockOptionLevel = serializers.IntegerField()
    TotalWorkingYears = serializers.IntegerField()
    TrainingTimesLastYear = serializers.IntegerField()
    WorkLifeBalance = serializers.IntegerField()
    YearsAtCompany = serializers.IntegerField()
    YearsInCurrentRole = serializers.IntegerField()
    YearsSinceLastPromotion = serializers.IntegerField()
    YearsWithCurrManager = serializers.IntegerField()
    BusinessTravel = serializers.CharField(max_length=77)
    Department = serializers.CharField(max_length=77)
    EducationField = serializers.CharField(max_length=77)
    Gender = serializers.CharField(max_length=77)
    JobRole = serializers.CharField(max_length=77)
    MaritalStatus = serializers.CharField(max_length=77)
    OverTime = serializers.CharField(max_length=77)

