# Generated by Django 5.2.9 on 2026-03-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ML', '0002_avocado_bank_diabetes_house_mushroom_telecom_titanic'),
    ]

    operations = [
        migrations.CreateModel(
            name='HREmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('DailyRate', models.IntegerField()),
                ('DistanceFromHome', models.IntegerField()),
                ('Education', models.IntegerField()),
                ('EnvironmentSatisfaction', models.IntegerField()),
                ('HourlyRate', models.IntegerField()),
                ('JobInvolvement', models.IntegerField()),
                ('JobLevel', models.IntegerField()),
                ('JobSatisfaction', models.IntegerField()),
                ('MonthlyIncome', models.IntegerField()),
                ('MonthlyRate', models.IntegerField()),
                ('NumCompaniesWorked', models.IntegerField()),
                ('PercentSalaryHike', models.IntegerField()),
                ('PerformanceRating', models.IntegerField()),
                ('RelationshipSatisfaction', models.IntegerField()),
                ('StockOptionLevel', models.IntegerField()),
                ('TotalWorkingYears', models.IntegerField()),
                ('TrainingTimesLastYear', models.IntegerField()),
                ('WorkLifeBalance', models.IntegerField()),
                ('YearsAtCompany', models.IntegerField()),
                ('YearsInCurrentRole', models.IntegerField()),
                ('YearsSinceLastPromotion', models.IntegerField()),
                ('YearsWithCurrManager', models.IntegerField()),
                ('BusinessTravel', models.CharField(max_length=77)),
                ('Department', models.CharField(max_length=77)),
                ('EducationField', models.CharField(max_length=77)),
                ('Gender', models.CharField(max_length=77)),
                ('JobRole', models.CharField(max_length=77)),
                ('MaritalStatus', models.CharField(max_length=77)),
                ('OverTime', models.CharField(max_length=77)),
            ],
        ),
    ]
